
[MAIL_TRIGGER]
port.mail                   = 587
host.mail                   = smtp.gmail.com
pass.mail                   = mnrkuczmyoeklstq
sender.mail                 = support@codifi.in
api_url.mail                = https://api.brevo.com/v3/smtp/email
app_key.mail                = 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

receiver.mail                = saran@codifi.in
#receiver.mail                = saran@codifi.in,,vinitha@codifi.in
developer.mail               = saran@codifi.in,daniel@codifi.in

try_Again.mail              = 3
try_sleep_time.mail         = 30

